CREATE_DB_QUERY = "CREATE DATABASE {};"
CREATE_TABLE_QUERY = "CREATE TABLE {} ({})"
SELECT_QUERY = "SELECT {} FROM {};"
FILTER_PART = "WHERE {}"
PAGINATION_PART = "LIMIT {} OFFSET {}"
ORDER_PART = "ORDERED BY {} {}"
FILTERS_DICT = {
    "COMPARE": "{} = {}",
    "LIKE": "{}",

}
INSERT_QUERY = "INSERT INTO {} ({}) VALUES ({});"
